### PR TITLE
Use port higher than 1024 to be able to run as a non-root user

### LINKED ISSUE #959: Katib Controller fails to run as non-root user in OpenShift
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

* Deploy Katib with `kfctl` on OpenShift 4.x cluster
  * You can follow this WIP PR: https://github.com/opendatahub-io/manifests/pull/4
* Katib Controller fails with error about not being able to bind to port `:443`

**What did you expect to happen:**

Katib Controller starts and runs successfully.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- OpenShift 4.x

### PR DESCRIPTION
**Pull request by vpavlin**
**What this PR does / why we need it**:
This PR allows Katib Controller to run as a non-root user. This is important from security point of view and especially to enable Katib on enterprise distributions of Kubernetes like OpenShift.

This PR adds a parameter `--webhook-port` to allow configuring port > 1024 for admission webhooks and also changes the default port (`443`) to `8443`.

It also changes the `USER` in `Dockerfile` as it is not necessary to run as root with this change even on the vanilla Kubernetes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #959

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

No image changes

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/960)

### CODE REVIEW

File: cmd/katib-controller/v1alpha3/main.go [hunk 1]
```diff
@@ -83,7 +85,7 @@ func main() {
 	}
 
 	log.Info("Setting up webhooks")
-	if err := webhook.AddToManager(mgr); err != nil {
+	if err := webhook.AddToManager(mgr, int32(webhookPort)); err != nil {
```
Comment (hougangliu) [inline cmd/katib-controller/v1alpha3/main.go]: why not `var webhookPort int32` in line 42?

File: cmd/katib-controller/v1alpha3/main.go [hunk 2]
```diff
@@ -39,10 +39,12 @@ func main() {
 
 	var experimentSuggestionName string
 	var metricsAddr string
+	var webhookPort int
 
 	flag.StringVar(&experimentSuggestionName, "experiment-suggestion-name",
 		"default", "The implementation of suggestion interface in experiment controller (default|fake)")
 	flag.StringVar(&metricsAddr, "metrics-addr", ":8080", "The address the metric endpoint binds to.")
+	flag.IntVar(&webhookPort, "webhook-port", 443, "The port number to be used for admission webhook server.")
```
Comment (hougangliu) [inline cmd/katib-controller/v1alpha3/main.go]: keep 8443 as default value

File: cmd/katib-controller/v1alpha3/main.go (hunk 1 above)
Comment (vpavlin) [reply cmd/katib-controller/v1alpha3/main.go]: Because defining the variable as `int32` fails in `flag.IntVar` with 

```
v1alpha3/main.go:47:14: cannot use &webhookPort (type *int32) as type *int in argument to flag.IntVar
```

So I tried `flag.Var`, but `int32` does not have `flag.Set` method implemented

```
*int32 does not implement flag.Value (missing Set method)
```

So the simplest solution seemed to be to just load `int` and change the type. Do you have different suggestion for solution?

File: cmd/katib-controller/v1alpha3/main.go (hunk 2 above)
Comment (vpavlin) [reply cmd/katib-controller/v1alpha3/main.go]: Done
