### PR TITLE
Don't check if trial's metadata is in spec.parameters 

### LINKED ISSUE #1844: Trial name could not be passed to env
/kind bug

**What steps did you take and what happened:**
I am trying to get access to the trial name from the trial's pod (I need it to build S3 bucket path for trained model).
I follow [this example](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/trial-template/trial-metadata-substitution.yaml#L69). 
But I've got an error 
```
Error from server: error when creating "trial-metadata-substitution.yaml": admission webhook "validator.experiment.katib.kubeflow.org" denied the request: parameter reference ${trialSpec.Name} does not exist in spec.parameters: [{lr double {0.03 0.01 [] }}]
```

This example itself does not work.

**What did you expect to happen:**
Trials running with env TRIAL_NAME resolved as trail's name.

**Anything else you would like to add:**
This example was working on Katib 0.12.0. 
It looks like additional check added in this [PR](https://github.com/kubeflow/katib/pull/1726) might cause this issue. One of the resolution might be to skip this check [here](https://github.com/kubeflow/katib/blob/master/pkg/webhook/v1beta1/experiment/validator/validator.go#L313) if it's trial metadata   ([such as name, kind, apiversion etc.](https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/consts/const.go#L158)).

But I will be happy with any other solution which allows me to pass trial name to pod as environment variable.

**Environment:**

- Katib version (check the Katib controller image version): 0.13.0
- Kubernetes version: 1.22
- OS : CentOS

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

### PR DESCRIPTION
**Pull request by alexeygorobets**
This PR fixes validation of Experiment when trial metadata used in template substitution.
Validator should not look for parameter in the spec.parameters if it is trial's metadata.

**Which issue(s) this PR fixes**:
Fixes #1844

### CODE REVIEW

**Comment by alexeygorobets** [comment]
cc @johnugeorge @henrysecond1

**Comment by tenzen-y** [comment]
Thanks for creating this @alexeygorobets!
Could you sign CLA on this [page](https://cla.developers.google.com/)?

**Comment by alexeygorobets** [comment]
hi @tenzen-y, just signed CLA, thanks

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by tenzen-y** [comment]
Since `kubeflow-katib-presubmit` failed due to dockerhub's pull limit, let's retry the test in a few hours with `/retest`.

> error building image: GET https://index.docker.io/v2/library/python/manifests/3.9: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenti
cating and upgrading: https://www.docker.com/increase-rate-limit

File: pkg/webhook/v1beta1/experiment/validator/validator.go [hunk 1]
```diff
@@ -311,8 +311,13 @@ func (g *DefaultValidator) validateTrialTemplate(instance *experimentsv1beta1.Ex
 
 		// Check if parameter reference exist in experiment parameters
 		if len(experimentParameterNames) > 0 {
-			if _, ok := experimentParameterNames[parameter.Reference]; !ok {
-				return fmt.Errorf("parameter reference %v does not exist in spec.parameters: %v", parameter.Reference, instance.Spec.Parameters)
+			// Check if parameter is trial metadata
+			regex := regexp.MustCompile(consts.TrialTemplateMetaReplaceFormatRegex)
+			match := regex.FindStringSubmatch(parameter.Reference)
+			if !(len(match) > 0 && contains(consts.TrialTemplateMetaKeys, match[1])) {
```
Comment (tenzen-y) [inline pkg/webhook/v1beta1/experiment/validator/validator.go:317]: I think `contains(contains(consts.TrialTemplateMetaKeys, match[1]))` returns `false` when `parameter.Reference` is `Anotations` or `Labels`. 
WDYT @alexeygorobets ?

https://github.com/kubeflow/katib/blob/e031b5eeb437e3966166c455666ba97c2b68a414/examples/v1beta1/trial-template/trial-metadata-substitution.yaml#L43-L48

**Review by tenzen-y — COMMENTED** [review]
Great contribution @alexeygorobets !
I left a few comments.

File: pkg/webhook/v1beta1/experiment/validator/validator_test.go [hunk 2]
```diff
@@ -570,6 +572,16 @@ spec:
...
+		// Trial template contains Trial metadata parameter substitution
+		{
+			Instance: func() *experimentsv1beta1.Experiment {
+				i := newFakeInstance()
+				i.Spec.TrialTemplate.TrialParameters[1].Reference = "${trialSpec.Name}"
+				return i
+			}(),
+			Err:             false,
+			testDescription: "Trial template contains Trial metadata reference as parameter",
+		},
```
Comment (tenzen-y) [inline pkg/webhook/v1beta1/experiment/validator/validator_test.go:584]: Could you add a test case for `Labels` or `Annotations`?

Comment (alexeygorobets) [reply pkg/webhook/v1beta1/experiment/validator/validator_test.go:588]: hi @tenzen-y , I've added handing of those cases and tests, thanks!

**Review by tenzen-y — APPROVED** [review]
Thanks for updating PR @alexeygorobets !
/lgtm

Could you please restart GitHub Actions @kubeflow/wg-automl-leads ?

**Comment by johnugeorge** [comment]
Thanks @alexeygorobets for this PR

/approve
