### PR TITLE
Reimplement katib-cert-generator in Go

### LINKED ISSUE #1628: Katib not ready for K8s 1.22
/kind bug

With the new Kubernetes 1.22 release, some APIs have been removed: https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/

The katib project still uses some of these APIs and will therefore not work on k8s 1.22.

For example, the following CRDs are still using `apiextensions.k8s.io/v1beta1`:
```
trials.kubeflow.org
suggestions.kubeflow.org
experiments.kubeflow.org
```

### PR DESCRIPTION
**Pull request by tenzen-y**
**What this PR does / why we need it**:
- Reimplement katib-cert-generator in Go.
- ~~Support both `admission.k8s.io/v1` and `admission.k8s.io/v1beta1` in ValidatingWebhookConfiguration and MutatingWebhookConfiguration.~~
- Remove `admission.k8s.io/v1beta1` in ValidatingWebhookConfiguration and MutatingWebhookConfiguration.

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #1628 #1656

### CODE REVIEW

**Comment by tenzen-y** [comment]
I removed unnecessary test codes and changed an error message.

**Comment by gaocegege** [comment]
ok-to-test

File: pkg/cert/v1beta1/generate/generate.go [hunk 1]
```diff
@@ -0,0 +1,263 @@
...
+	mutatingConf := &admissionregistrationv1.MutatingWebhookConfiguration{}
+	if err := kubeClient.GetResources(ctx, client.ObjectKey{Name: consts.Webhook}, mutatingConf); err != nil {
+		return err
+	}
+	newMutatingConf := mutatingConf.DeepCopy()
+	newMutatingConf.Webhooks[0].ClientConfig.CABundle = caKeypair.certPem
+	newMutatingConf.Webhooks[1].ClientConfig.CABundle = caKeypair.certPem
+
+	klog.Info("Trying to patch MutatingWebhookConfiguration adding the caBundle.")
+	for i := 0; i <= 5; i++ {
```
Comment (gaocegege) [inline pkg/cert/v1beta1/generate/generate.go:249]: Can we avoid magic numbers here? Maybe we can define it as a constant

File: pkg/cert/v1beta1/kube/client.go [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+)
+
+type Client struct {
+	KubeClient client.Client
+}
+
+func (c *Client) getKubeClient() (client.Client, error) {
+	if c.KubeClient == nil {
+		var err error
+		if c.KubeClient, err = client.New(config.GetConfigOrDie(), client.Options{Scheme: scheme.Scheme}); err != nil {
```
Comment (gaocegege) [inline pkg/cert/v1beta1/kube/client.go:32]: Will it be used by multiple goroutines? Should we keep it safe with once.Do?

**Review by gaocegege — COMMENTED** [review]
Thanks for your contribution! :tada: :+1:

The code is clean and elegant.

File: pkg/cert/v1beta1/generate/generate.go (hunk 1 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/generate/generate.go]: Thanks, I fixed it.

File: pkg/cert/v1beta1/kube/client.go (hunk 2 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/kube/client.go]: It makes sense. I fixed it.

File: manifests/v1beta1/components/webhook/webhooks.yaml [hunk 3]
```diff
@@ -6,8 +6,8 @@ webhooks:
   - name: validator.experiment.katib.kubeflow.org
     sideEffects: None
     failurePolicy: Ignore
-    # TODO (andreyvelich): Migrate to v1 ?
     admissionReviewVersions:
+      - v1
       - v1beta1
```
Comment (andreyvelich) [inline manifests/v1beta1/components/webhook/webhooks.yaml:11]: v1beta1 was deprecated in Kubernetes 1.16.
Since 1.16 is not longer maintained by Kubernetes team, should we keep only v1 ?
WDYT @tenzen-y @gaocegege @johnugeorge ?

File: pkg/cert/v1beta1/cert.go [hunk 4]
```diff
@@ -0,0 +1,33 @@
+/*
```
Comment (andreyvelich) [inline pkg/cert/v1beta1/cert.go:1]: Let's keep the name `pkg/cert-generator` to be consistent.

File: pkg/cert/v1beta1/consts/const.go [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+
+const (
+	CAName  = "katib-ca"
+	Service = "katib-controller"
+	JobName = "katib-cert-generator"
+	Secret  = "katib-webhook-cert"
+	Webhook = "katib.kubeflow.org"
+)
+
+const MaxTryPatchCount = 5
```
Comment (andreyvelich) [inline pkg/cert/v1beta1/consts/const.go:27]: Keep it in the same const.
```suggestion
	Webhook = "katib.kubeflow.org"
	MaxTryPatchCount = 5
)

```

File: pkg/cert/v1beta1/cert.go [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+	"github.com/kubeflow/katib/pkg/cert/v1beta1/generate"
+	"github.com/spf13/cobra"
+	"sigs.k8s.io/controller-runtime/pkg/client"
+)
+
+func NewKatibCertGeneratorCmd(kubeClient client.Client) (*cobra.Command, error) {
+	cmd := &cobra.Command{
+		Use:   "katib-cert-generator",
+		Short: "katib-cert-generator",
+		Long:  "katib-cert-generator",
```
Comment (andreyvelich) [inline pkg/cert/v1beta1/cert.go:29]: Maybe use the name from costs (JobName) ?

File: pkg/cert/v1beta1/generate/generate.go [hunk 7]
```diff
@@ -0,0 +1,262 @@
...
+	}
+	f := cmd.Flags()
+	f.StringVarP(&o.namespace, "namespace", "n", "kubeflow", "set namespace")
+	return cmd
+}
+
+func (o *generateOptions) run(ctx context.Context, kubeClient client.Client) error {
+	o.fullServiceDomain = strings.Join([]string{consts.Service, o.namespace, "svc"}, ".")
+
+	caKeyPair := &certificates{}
```
Comment (andreyvelich) [inline pkg/cert/v1beta1/generate/generate.go:67]: Do we need to send empty `&certificates{}` to `createCACert` function ?
Is there any use-case when we should populate `certificates{}` before executing `createCACert` ?
If not, maybe it makes sense to just return `*certificates` from the `createCACert` function ?

WDYT @tenzen-y ?

File: pkg/cert/v1beta1/generate/generate.go [hunk 8]
```diff
@@ -0,0 +1,262 @@
...
+	if err := o.createCACert(caKeyPair); err != nil {
+		return err
+	}
+	keyPair := &certificates{}
```
Comment (andreyvelich) [inline pkg/cert/v1beta1/generate/generate.go:71]: Similar comment as for `createCACert` ?

File: pkg/cert/v1beta1/generate/generate.go [hunk 9]
```diff
@@ -0,0 +1,262 @@
...
+	return nil
+}
+
+func (o *generateOptions) createCACert(caKeyPair *certificates) error {
+	now := time.Now()
+	template := &x509.Certificate{
+		SerialNumber: big.NewInt(0),
+		Subject: pkix.Name{
+			CommonName:   consts.CAName,
+			Organization: []string{"katib"},
```
Comment (andreyvelich) [inline pkg/cert/v1beta1/generate/generate.go:92]: Can we move `katib` to consts ?

File: pkg/cert/v1beta1/generate/generate.go [hunk 10]
```diff
@@ -0,0 +1,262 @@
...
+		return err
+	}
+	if err = keyPair.encode(x509.MarshalPKCS1PrivateKey(keyPair.key), der); err != nil {
+		return err
+	}
+	klog.Info("Generate public certificate and private key signed with self-singed CA cert and private key.")
+	return nil
+}
+
+// createWebhookCertSecret create Secret embedded ca.key, ca.crt, tls.key and tls.cert
```
Comment (andreyvelich) [inline pkg/cert/v1beta1/generate/generate.go:158]:
```suggestion
// createWebhookCertSecret creates Secret embedded ca.key, ca.crt, tls.key and tls.cert
```

Comment (andreyvelich) [inline pkg/cert/v1beta1/generate/generate.go:158]: Please can you also add comments for other functions ?

File: pkg/cert/v1beta1/generate/generate.go [hunk 11]
```diff
@@ -0,0 +1,262 @@
...
+					Controller: pointer.BoolPtr(true),
+					Name:       consts.JobName,
+					UID:        jobUID,
+				},
+			},
+		},
+		Type: corev1.SecretTypeTLS,
+		Data: map[string][]byte{
+			"ca.key":  caKeyPair.keyPem,
+			"ca.crt":  caKeyPair.certPem,
```
Comment (andreyvelich) [inline pkg/cert/v1beta1/generate/generate.go:190]: Why previously we added only `tls.key` and `tls.crt`: https://github.com/kubeflow/katib/blob/master/hack/cert-generator.sh#L150-L151 ?

File: pkg/cert/v1beta1/generate/generate.go [hunk 12]
```diff
@@ -0,0 +1,262 @@
...
+	}
+
+	klog.Infof("Creating Secret: %s", consts.Secret)
+	if err = kubeClient.Create(ctx, webhookCertSecret); err != nil {
+		return err
+	}
+	return nil
+}
+
+// injectCert apply patch to ValidatingWebhookConfiguration and MutatingWebhookConfiguration
```
Comment (andreyvelich) [inline pkg/cert/v1beta1/generate/generate.go:215]:
```suggestion
// injectCert applies patch to ValidatingWebhookConfiguration and MutatingWebhookConfiguration
```

File: pkg/cert/v1beta1/generate/generate.go [hunk 13]
```diff
@@ -0,0 +1,262 @@
...
+func (o *generateOptions) injectCert(ctx context.Context, kubeClient client.Client, caKeypair *certificates) error {
+	validatingConf := &admissionregistrationv1.ValidatingWebhookConfiguration{}
+	if err := kubeClient.Get(ctx, client.ObjectKey{Name: consts.Webhook}, validatingConf); err != nil {
+		return err
+	}
+	newValidatingConf := validatingConf.DeepCopy()
+	newValidatingConf.Webhooks[0].ClientConfig.CABundle = caKeypair.certPem
+
+	klog.Info("Trying to patch ValidatingWebhookConfiguration adding the caBundle.")
+	for i := 0; i <= consts.MaxTryPatchCount; i++ {
```
Comment (andreyvelich) [inline pkg/cert/v1beta1/generate/generate.go:225]: What is the use-case when we can't patch it from the first time ?
Does that happen when cert-generator job starts before `ValidatingWebhookConfiguration` was created ?

File: pkg/cert/v1beta1/generate/generate_test.go [hunk 14]
```diff
@@ -0,0 +1,173 @@
...
+			UID:       "test",
+		},
+	}
+	testValidatingWebhook := &admissionregistration.ValidatingWebhookConfiguration{
+		TypeMeta: metav1.TypeMeta{
+			APIVersion: "admissionregistration.k8s.io/v1",
+			Kind:       "ValidatingWebhookConfiguration",
+		},
+		ObjectMeta: metav1.ObjectMeta{
+			Name: "katib.kubeflow.org",
```
Comment (andreyvelich) [inline pkg/cert/v1beta1/generate/generate_test.go:53]: Take it from consts ?

File: pkg/cert/v1beta1/generate/generate_test.go [hunk 15]
```diff
@@ -0,0 +1,173 @@
...
+			APIVersion: "v1",
+		},
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      consts.Secret,
+			Namespace: testNamespace,
+		},
+	}
+
+	tests := []struct {
+		name      string
```
Comment (andreyvelich) [inline pkg/cert/v1beta1/generate/generate_test.go:100]: Let's keep the name `testDescription` to be consistent with other ut:
https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/suggestion/composer/composer_test.go#L147
https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go#L192

Does it sound good @tenzen-y ?

**Review by andreyvelich — COMMENTED** [review]
Thank you so much for doing this @tenzen-y!
I left few comments.

File: manifests/v1beta1/components/webhook/webhooks.yaml (hunk 3 above)
Comment (gaocegege) [reply manifests/v1beta1/components/webhook/webhooks.yaml:11]: I think so.

File: cmd/cert-generator/v1beta1/Dockerfile [hunk 16]
```diff
@@ -1,13 +1,29 @@
...
+RUN if [ "$(uname -m)" = "ppc64le" ]; then \
+    CGO_ENABLED=0 GOOS=linux GOARCH=ppc64le go build -a -o katib-cert-generator ./cmd/cert-generator/v1beta1; \
+    elif [ "$(uname -m)" = "aarch64" ]; then \
+    CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -a -o katib-cert-generator ./cmd/cert-generator/v1beta1; \
+    else \
+    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o katib-cert-generator ./cmd/cert-generator/v1beta1; \
+    fi
+
+# Copy the cert-generator into a thin image.
+FROM gcr.io/distroless/static:nonroot
```
[the remark this answers is not in the document]
Comment (tenzen-y) [reply cmd/cert-generator/v1beta1/Dockerfile:25]: I used the distroless image because I didn't think the cert-generator needed a shell. 
What do you think about it? @andreyvelich

File: cmd/cert-generator/v1beta1/Dockerfile [hunk 17]
```diff
@@ -1,13 +1,29 @@
-FROM alpine:3.12.4
+# Build the Katib Cert Generatoe.
```
[the remark this answers is not in the document]
Comment (tenzen-y) [reply cmd/cert-generator/v1beta1/Dockerfile]: Thanks !

File: go.mod [hunk 18]
```diff
@@ -20,16 +20,18 @@ require (
...
 	golang.org/x/net v0.0.0-20210405180319-a5a99cb37ef4
-	google.golang.org/grpc v1.32.0
+	google.golang.org/grpc v1.38.0
 	gopkg.in/fsnotify/fsnotify.v1 v1.4.7 // indirect
 	k8s.io/api v0.20.4
 	k8s.io/apimachinery v0.20.4
 	k8s.io/client-go v0.20.4
 	k8s.io/klog v1.0.0
 	k8s.io/kube-openapi v0.0.0-20210216185858-15cd8face8d6
+	k8s.io/utils v0.0.0-20210707171843-4b05e18ac7d9
```
[the remark this answers is not in the document]
Comment (tenzen-y) [reply go.mod]: It sounds good.  I fixed it.

File: manifests/v1beta1/components/cert-generator/cert-generator.yaml [hunk 19]
```diff
@@ -12,14 +12,20 @@ spec:
...
           imagePullPolicy: Always
+          command: ["./katib-cert-generator"]
+          args: ["generate", "--namespace=$(KATIB_CORE_NAMESPACE)"]
           env:
             - name: KATIB_CORE_NAMESPACE
               valueFrom:
                 fieldRef:
                   fieldPath: metadata.namespace
+          securityContext:
+            allowPrivilegeEscalation: false
```
[the remark this answers is not in the document]
Comment (tenzen-y) [reply manifests/v1beta1/components/cert-generator/cert-generator.yaml]: Sorry, I forgot that PSP is deprecated.
I fixed it.

File: manifests/v1beta1/components/webhook/webhooks.yaml (hunk 3 above)
Comment (tenzen-y) [reply manifests/v1beta1/components/webhook/webhooks.yaml:11]: I left v1beta1 because of the following in the kubeflow documentation.

https://www.kubeflow.org/docs/distributions/aws/deploy/eks-compatibility/

If it is the policy of the Katib community not to support versions of Kubernetes that are not maintained by Kubernetes team, I am in favor of removing v1beta1.

File: pkg/cert/v1beta1/cert.go (hunk 4 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/cert.go]: It makes sense.
I fixed it.

File: pkg/cert/v1beta1/consts/const.go (hunk 5 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/consts/const.go]: Thanks!

File: pkg/cert/v1beta1/cert.go (hunk 6 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/cert.go]: It makes sense.
I fixed it.

**Comment by tenzen-y** [comment]
> @tenzen-y Is that correct that after this implementation we are not going to use [`CertificateSigningRequest`](https://github.com/kubeflow/katib/blob/master/hack/cert-generator.sh#L75) ?

@andreyvelich 
Yes. 
In this implement, cert-generator sign the server-cert using self-signed CA cert and key. So, we do not have to create CertificateSigningRequest.

**Comment by tenzen-y** [comment]
@googlebot I consent.

**Comment by tenzen-y** [comment]
@andreyvelich 
Can you comment `@googlebot I consent.`, please?

File: pkg/cert/v1beta1/generate/generate.go (hunk 7 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/generate/generate.go]: > Is there any use-case when we should populate certificates{} before executing createCACert ?
If not, maybe it makes sense to just return *certificates from the createCACert function ?

Currently, there is no such use-case. So, your suggestion makes sense.

File: pkg/cert/v1beta1/generate/generate.go (hunk 8 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/generate/generate.go]: Same as `createCACert`.

**Comment by andreyvelich** [comment]
@googlebot I consent.

File: cmd/cert-generator/v1beta1/Dockerfile (hunk 16 above)
[the remark this answers is not in the document]
Comment (andreyvelich) [reply cmd/cert-generator/v1beta1/Dockerfile:25]: Sounds good, eventually this job is running very fast.

File: manifests/v1beta1/components/cert-generator/cert-generator.yaml [hunk 20]
```diff
@@ -12,10 +12,14 @@ spec:
         sidecar.istio.io/inject: "false"
     spec:
       serviceAccountName: katib-cert-generator
+      securityContext:
+        runAsNonRoot: true
```
Comment (andreyvelich) [inline manifests/v1beta1/components/cert-generator/cert-generator.yaml:16]: Also, why do we need this ?

File: manifests/v1beta1/components/webhook/webhooks.yaml (hunk 3 above)
Comment (andreyvelich) [reply manifests/v1beta1/components/webhook/webhooks.yaml:11]: AWS distribution has not been updated for Kubeflow 1.3
I think we can say that Katib is working on Kubernetes >= 1.17
It should be fine for the community, otherwise they can use older version of Katib.

Comment (tenzen-y) [reply manifests/v1beta1/components/webhook/webhooks.yaml:11]: It makes sense. I'd like to remove v1beta1 from `manifests/v1beta1/components/webhook/webhooks.yaml`.

In addition, I think it needs to be documented that Katib 0.12 supports K8s => 1.17. in `Readme.md` or changelog. What do you think? @andreyvelich

File: cmd/cert-generator/v1beta1/Dockerfile (hunk 16 above)
[the remark this answers is not in the document]
Comment (tenzen-y) [reply cmd/cert-generator/v1beta1/Dockerfile:25]: > eventually this job is running very fast.

I don't think it's a problem because cert-generator try to patch ValidatingWebhookConfiguration and MutatingWebhookConfiguration many times.

- https://github.com/kubeflow/katib/pull/1662/files#diff-1e723681ebf78f0d21f485dadc2b6e8a5762277daa25d4a8b0c65f2b188b5a40R225
- https://github.com/kubeflow/katib/pull/1662/files#diff-1e723681ebf78f0d21f485dadc2b6e8a5762277daa25d4a8b0c65f2b188b5a40R248

[the remark this answers is not in the document]
Comment (tenzen-y) [reply cmd/cert-generator/v1beta1/Dockerfile:25]: > > eventually this job is running very fast.
> 
> I don't think it's a problem because cert-generator try to patch ValidatingWebhookConfiguration and MutatingWebhookConfiguration many times.
> 
> * https://github.com/kubeflow/katib/pull/1662/files#diff-1e723681ebf78f0d21f485dadc2b6e8a5762277daa25d4a8b0c65f2b188b5a40R225
> * https://github.com/kubeflow/katib/pull/1662/files#diff-1e723681ebf78f0d21f485dadc2b6e8a5762277daa25d4a8b0c65f2b188b5a40R248

Sorry, I was mistaken. Ignore this comment, please.

File: pkg/cert/v1beta1/generate/generate.go (hunk 13 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/generate/generate.go]: > > Does that happen when cert-generator job starts before ValidatingWebhookConfiguration was created ?

I implemented the same as previously.

https://github.com/kubeflow/katib/blob/master/hack/cert-generator.sh#L162

Now that I think about it, once is enough. I'd like to fix it.

File: pkg/cert/v1beta1/generate/generate_test.go (hunk 15 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/generate/generate_test.go]: Sure, sounds good!

File: pkg/cert/v1beta1/generate/generate.go (hunk 9 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/generate/generate.go]: Sure.
I fixed it.

File: pkg/cert/v1beta1/generate/generate.go (hunk 7 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/generate/generate.go]: I fixed it.

File: pkg/cert/v1beta1/generate/generate.go (hunk 8 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/generate/generate.go]: I fixed it.

File: pkg/cert/v1beta1/generate/generate.go (hunk 10 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/generate/generate.go]: Sure.

File: pkg/cert/v1beta1/generate/generate.go (hunk 12 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/generate/generate.go]: I fixed it.

File: pkg/cert/v1beta1/generate/generate.go (hunk 10 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/generate/generate.go]: I fixed it.

Comment (tenzen-y) [reply pkg/cert/v1beta1/generate/generate.go]: I added comments to other functions.

File: pkg/cert/v1beta1/generate/generate.go (hunk 11 above)
Comment (tenzen-y) [reply pkg/cert/v1beta1/generate/generate.go]: In the previous implementation, katib-cert-generator(KCG) creates a CertificateSigningRequest Resource (kubeCSR) containing a CSR and approves the kubeCSR using `kubectl approve`. Then the signing controller will sign it with the CA certificate and add the certificate to the status.certificate field of the kubeCSR. Finally, the webhook server functions by registering the CA certificate in FooWebhookConfiguration. 

In this implementation, KCG creates a CA certificate to sign the server certificate (`ca.crt` & `ca.key`) to use signing the server certificate (`tls.crt` & `tls.key`). Then, the webhook server functions by registering the first CA certificate to BarWebhookConfiguration.

Therefore, we previously added only `tls.crt` and `tls.key` to Secret.

Thanks for reading my explanation.

File: manifests/v1beta1/components/cert-generator/cert-generator.yaml (hunk 20 above)
Comment (tenzen-y) [reply manifests/v1beta1/components/cert-generator/cert-generator.yaml:16]: Generally, containers should run as a non-root user. Fortunately,  katib-cert-generator does not have any features that must use privileges. So, I set true in securityContext.runAsNonRoot filed.

By the way, other components(ex: katib-controller) use the alpine image and do not prohibit running as a root user. I consider we should use the distroless image and do not permit running as a root user.

WDYT @andreyvelich ?

Comment (andreyvelich) [reply manifests/v1beta1/components/cert-generator/cert-generator.yaml:16]: In `distroless` image can we execute in the container to debug it ?
Do you know what is security issues are we getting by running these containers as root ?
I thought we should be consistent across Katib components.

cc @gaocegege @johnugeorge

File: pkg/cert/v1beta1/generate/generate.go (hunk 11 above)
Comment (andreyvelich) [reply pkg/cert/v1beta1/generate/generate.go]: Thank you for the explanation @tenzen-y!

File: manifests/v1beta1/components/webhook/webhooks.yaml (hunk 3 above)
Comment (andreyvelich) [reply manifests/v1beta1/components/webhook/webhooks.yaml]: > In addition, I think it needs to be documented that Katib supports K8s => 1.17. 

That's a good point, I will point this during refactoring README: https://github.com/kubeflow/katib/issues/1570

File: pkg/cert-generator/v1beta1/generate/generate.go [hunk 21]
```diff
@@ -0,0 +1,243 @@
...
+		Short:        "generate server cert for webhook",
+		Long:         "generate server cert for webhook",
+		SilenceUsage: true,
+		RunE: func(cmd *cobra.Command, args []string) error {
+			if err := o.run(context.TODO(), kubeClient); err != nil {
+				return err
+			}
+			return nil
+		},
+	}
```
Comment (andreyvelich) [inline pkg/cert-generator/v1beta1/generate/generate.go:59]: Sorry that I haven't asked about it before.
Since we have only 1 entrypoint command `generate`, do we need `cobra` command in this script ?
Are we planing to extend this script in the future with additional commands (e.g. `update`) ?

If not, we might simplify it to use just command line arguments (similar to [`katib-controller`](https://github.com/kubeflow/katib/blob/master/cmd/katib-controller/v1beta1/main.go#L52-L65)).

What do you think @tenzen-y @gaocegege ?

File: manifests/v1beta1/components/cert-generator/cert-generator.yaml (hunk 20 above)
Comment (tenzen-y) [reply manifests/v1beta1/components/cert-generator/cert-generator.yaml:16]: > In distroless image can we execute in the container to debug it ?

Sorry, I thought we could debug the container using `kubectl debug` command, but I found an ephemeral debug container is an alpha feature.

https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container

So, I think we could reconsider distroless images when is ephemeral debug containers feature is available by default.

> Do you know what is security issues are we getting by running these containers as root ?

I can not show you anything other than the security recommendation in  K8s documentation.

https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/#controlling-what-privileges-containers-run-with

File: pkg/cert-generator/v1beta1/generate/generate.go (hunk 21 above)
Comment (tenzen-y) [reply pkg/cert-generator/v1beta1/generate/generate.go:59]: I'm not planning it.
I implemented using cobra because I thought it would give me better visibility.

File: manifests/v1beta1/components/cert-generator/cert-generator.yaml (hunk 20 above)
Comment (andreyvelich) [reply manifests/v1beta1/components/cert-generator/cert-generator.yaml:16]: > So, I think we could reconsider distroless images when is ephemeral debug containers feature is available by default.

Maybe, let's create an issue to track it ? We might have to add `runAsNonRoot: true`  for all of our Katib components in the future.

File: pkg/cert-generator/v1beta1/generate/generate.go (hunk 21 above)
Comment (andreyvelich) [reply pkg/cert-generator/v1beta1/generate/generate.go:59]: Sounds good.
What do you think about it @johnugeorge @gaocegege ?

File: manifests/v1beta1/components/cert-generator/cert-generator.yaml (hunk 20 above)
Comment (tenzen-y) [reply manifests/v1beta1/components/cert-generator/cert-generator.yaml:16]: It sounds good!
In this PR, I'd like to remove securityContext field. In addition, I'd like to create an issue about it.

Comment (tenzen-y) [reply manifests/v1beta1/components/cert-generator/cert-generator.yaml:16]: I created an Issue.
https://github.com/kubeflow/katib/issues/1664

Comment (andreyvelich) [reply manifests/v1beta1/components/cert-generator/cert-generator.yaml:16]: Thank you @tenzen-y!

Comment (tenzen-y) [reply manifests/v1beta1/components/cert-generator/cert-generator.yaml]: I removed the securityContext field!

File: pkg/cert-generator/v1beta1/generate/generate.go (hunk 21 above)
Comment (johnugeorge) [reply pkg/cert-generator/v1beta1/generate/generate.go:59]: It looks ok to me

**Review by andreyvelich — COMMENTED** [review]
Thank you for this great contribution @tenzen-y!
/lgtm
@gaocegege @johnugeorge Please take a look.

File: pkg/cert-generator/v1beta1/generate/generate.go (hunk 21 above)
Comment (gaocegege) [reply pkg/cert-generator/v1beta1/generate/generate.go:59]: LGTM

**Review by gaocegege — APPROVED** [review]
LGTM :+1:
/lgtm

Thanks for your contribution! :tada: :+1:

**Comment by tenzen-y** [comment]
Thanks for the review! @andreyvelich @johnugeorge @gaocegege
