### PR TITLE
fix: clean up UTs for file metrics collector

### LINKED ISSUE #1756: Add unit tests for File Metrics Collector
/kind feature

We should add unit test for our [File Metrics Collector](https://github.com/kubeflow/katib/tree/master/pkg/metricscollector/v1beta1/file-metricscollector) to verify log parsing. 
That will help to avoid issues similar to: https://github.com/kubeflow/katib/issues/1754

/help
/good-first-issue

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

### PR DESCRIPTION
**Pull request by Electronic-Waste**
**What this PR does / why we need it**:

Current error comparison in file-metricscollector_test.go is based on a boolean rather than the error content  To make test cases more detailed and accurate, we should expose and compare errors. 

And also @tenzen-y suggested that `t.TempDir` should be used for generating test directory. So I replace static directories with `t.TempDir`.

Related discussion: https://github.com/kubeflow/katib/issues/1756#issuecomment-1983711306 https://github.com/kubeflow/katib/pull/2274#discussion_r1521725542

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #1756 

**Checklist:**

- [x] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Comment by Electronic-Waste** [comment]
PTAL👀 @andreyvelich @tenzen-y . BTW my flag is standing :)

File: pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go [hunk 1]
```diff
@@ -309,8 +300,8 @@ func TestCollectObservationLog(t *testing.T) {
 	for name, test := range testCases {
 		t.Run(name, func(t *testing.T) {
 			actual, err := CollectObservationLog(test.filePath, test.metrics, test.filters, test.fileFormat)
```
Comment (tenzen-y) [inline pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go:302]:
```suggestion
	testMetricsFileName := "test-metrics"
	testCases := map[string]struct {
		testData string
		metrics    []string
		...
	}{
		"": {
			...
		},
		...
	}
	for name, test := range testCases {
		t.Run(name, func(t *testing.T) {
			tmpDir := t.TempDir()
			if len(test.testData) != 0 {
				if err := os.WriteFile(filepath.Join(tmpDir, testMetricsFileName), []byte(test.testData), 0600); err != nil {
					return t.Fatal(err)
				}
			}
			actual, err := CollectObservationLog(test.filePath, test.metrics, test.filters, test.fileFormat)
```

Once we introduce the `tmp` dir, the test data should be generated more declaratively.

File: pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go [hunk 2]
```diff
@@ -309,8 +300,8 @@ func TestCollectObservationLog(t *testing.T) {
...
-			if (err != nil) != test.err {
-				t.Errorf("\nGOT: \n%v\nWANT: %v\n", err, test.err)
+			if err != nil && err.Error() != test.errCause {
+				t.Errorf("Unexpected error (-want,+got):\n%s", cmp.Diff(test.errCause, err.Error()))
```
Comment (tenzen-y) [inline pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go:304]: We must not compare error strings.
Please refer to this example: https://github.com/kubeflow/katib/blob/6f372f68089c0a01d2c06e98489557a88e5a7183/pkg/util/v1beta1/katibconfig/config_test.go#L42

**Review by tenzen-y — COMMENTED** [review]
Give my first review

File: pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go (hunk 2 above)
Comment (Electronic-Waste) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go:304]: Okay, shall I define those errors in test cases directly?

File: pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go (hunk 1 above)
Comment (Electronic-Waste) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go:302]: Okay, I'll refactor the current code.

File: pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go (hunk 2 above)
Comment (tenzen-y) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go:304]: Checking here how to define and use errors: 

https://github.com/kubeflow/katib/blob/6f372f68089c0a01d2c06e98489557a88e5a7183/pkg/util/v1beta1/katibconfig/config.go#L38-L42

https://github.com/kubeflow/katib/blob/6f372f68089c0a01d2c06e98489557a88e5a7183/pkg/util/v1beta1/katibconfig/config.go#L144

Comment (Electronic-Waste) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go:304]: Do you mean that I need to modify the error msg returned in `file-metricscollector.go` and compare errors in `file-metricscollector_test.go`?

Comment (tenzen-y) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go:304]: Yes, I meant it.

Comment (Electronic-Waste) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go:304]: AFAIK, it will change the current error handling code in `file-metricscollector.go`

Comment (Electronic-Waste) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go:304]: Okay, I'll do it later.

File: pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go (hunk 1 above)
Comment (tenzen-y) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go:302]: I assumed the same as the currently one. (decription)

Comment (Electronic-Waste) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go:302]: Okay, I see.

**Comment by Electronic-Waste** [comment]
I reordered the judging logics in `CollectObservatoinLog`, for we should check the `fileFormat` first in case of opening an invalid file. (Or the test case `"Invalid file format"` will report "can't find file or directory error` since the order of test file generation is not sure.)

Also, some typical error's descriptions  are added to the returned error in `file-metricscollector`.

File: pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go [hunk 3]
```diff
@@ -34,15 +35,27 @@ import (
 	"github.com/kubeflow/katib/pkg/metricscollector/v1beta1/common"
 )
 
+var (
+	ErrFileFormat = fmt.Errorf("format must be set %v or %v", commonv1beta1.TextFormat, commonv1beta1.JsonFormat)
+	ErrOpenFile   = errors.New("failed to open the file")
+	ErrReadFile   = errors.New("failed to read the file")
+	ErrParseJson  = errors.New("failed to parse the json object")
```
Comment (tenzen-y) [inline pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go:42]:
```suggestion
	errFileFormat = fmt.Errorf("format must be set %v or %v", commonv1beta1.TextFormat, commonv1beta1.JsonFormat)
	errOpenFile   = errors.New("failed to open the file")
	errReadFile   = errors.New("failed to read the file")
	errParseJson  = errors.New("failed to parse the json object")
```

No need to expose these vars.

File: pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go [hunk 4]
```diff
@@ -52,7 +65,7 @@ func CollectObservationLog(fileName string, metrics []string, filters []string,
 	case commonv1beta1.JsonFormat:
 		return parseLogsInJsonFormat(strings.Split(logs, "\n"), metrics)
 	}
```
Comment (tenzen-y) [inline pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go:67]:
```suggestion
	default:
		return nil, nil
	}
```

File: pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go [hunk 5]
```diff
@@ -52,7 +65,7 @@ func CollectObservationLog(fileName string, metrics []string, filters []string,
...
-	return nil, fmt.Errorf("format must be set %v or %v", commonv1beta1.TextFormat, commonv1beta1.JsonFormat)
+	return nil, nil
```
Comment (tenzen-y) [inline pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go:68]:
```suggestion
```

File: pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go [hunk 6]
```diff
@@ -306,126 +308,21 @@ func TestCollectObservationLog(t *testing.T) {
...
 		t.Run(name, func(t *testing.T) {
-			actual, err := CollectObservationLog(test.filePath, test.metrics, test.filters, test.fileFormat)
-			if (err != nil) != test.err {
-				t.Errorf("\nGOT: \n%v\nWANT: %v\n", err, test.err)
-			} else {
-				if diff := cmp.Diff(test.expected, actual); diff != "" {
-					t.Errorf("Unexpected parsed result (-want,+got):\n%s", diff)
+			if test.testData != "" {
+				if err := os.WriteFile(filepath.Join(tmpDir, test.fileName), []byte(test.testData), 0600); err != nil {
+					t.Fatal(err)
```
Comment (tenzen-y) [inline pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go:316]:
```suggestion
					t.Fatalf("failed to write test data: %v", err)
```

**Review by tenzen-y — COMMENTED** [review]
Basically, lgtm

File: pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go (hunk 3 above)
Comment (Electronic-Waste) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go:42]: okay, I'll change it.

File: pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go (hunk 4 above)
Comment (Electronic-Waste) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go:67]: I see!

File: pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go (hunk 5 above)
Comment (Electronic-Waste) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go:68]: That makes sense. But it seems that the control flow won't reach them. Do we need to add this line for the neatness of the code?

Comment (tenzen-y) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go:68]: I meant to remove this line.

Comment (Electronic-Waste) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go:68]: Sorry. I meant the 'default' line.

File: pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go (hunk 4 above)
Comment (Electronic-Waste) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go:69]: Sorry, it seems okay for this change to make the switch clause tidy and neat. Plz ignore what I say in the comments below🤣.

Comment (tenzen-y) [reply pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go:69]: No worries.

**Comment by Electronic-Waste** [comment]
@tenzen-y  It seems that the CI failed due to other reasons which are not concerned with my code.

**Comment by tenzen-y** [comment]
> @tenzen-y It seems that the CI failed due to other reasons which are not concerned with my code.

I'll try to check it.

**Comment by tenzen-y** [comment]
@Electronic-Waste Could you rebase this PR? Because I fixed CI issues.

**Comment by Electronic-Waste** [comment]
@tenzen-y Sure! I'll rebase it soon.

**Comment by Electronic-Waste** [comment]
Some unexpected errors occurred in `Go Test / Unit Test (1.27.1) (pull_request)`

```
{"level":"info","ts":"2024-04-03T01:41:34Z","logger":"trial-controller","msg":"Trial status changed to Metrics Unavailable","Trial":{"name":"test-trial","namespace":"default"}}
--- FAIL: TestReconcileBatchJob (82.16s)
    trial_controller_test.go:274: 
        Timed out after 80.000s.
        Expected
            <bool>: false
        to be true
FAIL
```

Should we look into this error and fix it?

**Comment by tenzen-y** [comment]
> I encountered them many times in CI. Should we look into these errors and fix them?

Those errors are known flakness issues. I'll try to restart jobs.

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/lgtm
/approve

**Comment by Electronic-Waste** [comment]
@tenzen-y Thank you for your review!
