### PR TITLE
[enhance] change default metrics collect format

### LINKED ISSUE #1702: Metrics in scientific notation are not correctly parsed by default
/kind bug

This is an excerpt of a Log of one Trial: As you can see the Score is still correct in file-metricscollector.go:49 but is then wrongly parsed somewhere:
```
I1007 08:08:59.928474      73 main.go:136] Score=-7.539458549707136e-05

7.10.2021 10:09:01 W1007 08:09:01.339500      73 file-metricscollector.go:49] Metrics will not have timestamp since Score=-7.539458549707136e-05 doesn't begin with timestamp string

7.10.2021 10:09:01 I1007 08:09:01.348925      73 main.go:397] Metrics reported. :

7.10.2021 10:09:01 metric_logs:<time_stamp:"0001-01-01T00:00:00Z" metric:<name:"Score" value:"-7.539458549707136" > >
```

### PR DESCRIPTION
**Pull request by anencore94**
**What this PR does / why we need it**:
-  to parse scientific notation well

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #1702

**Checklist:**

- [x] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

File: pkg/metricscollector/v1beta1/common/const.go [hunk 1]
```diff
@@ -40,7 +40,10 @@ const (
 	// Metrics must be printed this way
 	// loss=0.3
 	// accuracy=0.98
-	DefaultFilter = `([\w|-]+)\s*=\s*((-?\d+)(\.\d+)?)`
+	// Score=-7.53e-05
```
Comment (andreyvelich) [inline pkg/metricscollector/v1beta1/common/const.go:43]: Please can you also add the following example, I believe it is supported.
```suggestion
	// Score=-7.53e-05
	// Score=-7.53e+05
```

**Review by andreyvelich — COMMENTED** [review]
Thank you for this update @anencore94!
Small comment from me.

**Comment by andreyvelich** [comment]
Also, please submit the PR to update documentation: https://www.kubeflow.org/docs/components/katib/experiment/#metrics-collector.
We add default metrics format there.
