### PR TITLE
fix(api): resolve all api voilation exceptions in katib api

### LINKED ISSUE #2479: Resolve API Violation Exceptions in Katib API
### What you would like to be added?

We should resolve API violation exceptions in:

https://github.com/kubeflow/katib/blob/eb8af4d50266b51c77ea895585ff535c8e9137f9/hack/violation_exception_v1beta1.list#L1-L30

### Why is this needed?

As we discussed in https://github.com/kubeflow/katib/pull/2463#discussion_r1878566117, we will create this issue as the tracker for resolving those API violation exceptions

/remove-label lifecycle/needs-triage
/good-first-issue
/area api

### Love this feature?

Give it a 👍 We prioritize the features with most 👍

### PR DESCRIPTION
**Pull request by truc0**
**What this PR does / why we need it**:

- resolve all api violation exceptions in katib api in `hack/violation_exception_v1beta1` https://github.com/kubeflow/katib/blob/eb8af4d50266b51c77ea895585ff535c8e9137f9/hack/violation_exception_v1beta1.list#L1-L30

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #2479 

**Checklist:**

- [x] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

File: pkg/apis/controller/common/v1beta1/common_types.go [hunk 1]
```diff
@@ -27,6 +27,9 @@ type AlgorithmSpec struct {
 	AlgorithmName string `json:"algorithmName,omitempty"`
 
 	// Key-value pairs representing settings for suggestion algorithms.
+	// +listType=map
+	// +listMapKey=Name
+	// +optional
```
Comment (Electronic-Waste) [inline pkg/apis/controller/common/v1beta1/common_types.go:32]: I think, we may not need the `+optional` tag, and the same as other `+optional` tag you added:)

**Review by Electronic-Waste — COMMENTED** [review]
Basically LGTM! Thanks for your great contribution @truc0. Welcome to Kubeflow Community🎉

/assign @kubeflow/wg-automl-leads @helenxie-bit @tariq-hasan

**Comment by helenxie-bit** [comment]
Thank you for your contribution and welcome to the Kubeflow community! The changes look good and I don’t have additional comments. LGTM! 😄

File: pkg/apis/controller/common/v1beta1/common_types.go (hunk 1 above)
Comment (truc0) [reply pkg/apis/controller/common/v1beta1/common_types.go:32]: Thanks for pointing out.

I have removed all `+optional` mark in the updated version ([d92c338](https://github.com/kubeflow/katib/commit/d92c3385e93d7abe24fc64d5a4195b9e08c2fc1f))~

PTAL if you have time.

**Review by Electronic-Waste — APPROVED** [review]
LGTM! Thanks for your great contributions!

/lgtm

**Comment by Electronic-Waste** [comment]
@truc0 The `Publish Katib Core Images` CI tests sometimes failed due to cache exporting errors. 

This PR https://github.com/kubeflow/katib/pull/2487 raised by @Doris-xm has fixed that error. The CI tests may pass more smoothly if you could rebase your PR:)

**Comment by truc0** [comment]
Thanks for your advice. The latest version ([a062fd1](https://github.com/kubeflow/katib/commit/a062fd10056292b429000ffb633945f781e0d754)) has rebased.

File: pkg/apis/controller/common/v1beta1/common_types.go [hunk 2]
```diff
@@ -27,6 +27,8 @@ type AlgorithmSpec struct {
 	AlgorithmName string `json:"algorithmName,omitempty"`
 
 	// Key-value pairs representing settings for suggestion algorithms.
+	// +listType=map
+	// +listMapKey=Name
```
Comment (andreyvelich) [inline pkg/apis/controller/common/v1beta1/common_types.go:31]: Should this Name be lowercase, like here: https://github.com/kubeflow/training-operator/blob/master/pkg/apis/kubeflow.org/v2alpha1/trainjob_types.go#L210 ?

File: pkg/apis/controller/experiments/v1beta1/experiment_types.go [hunk 3]
```diff
@@ -78,30 +80,39 @@ type ExperimentStatus struct {
 	LastReconcileTime *metav1.Time `json:"lastReconcileTime,omitempty"`
 
 	// List of observed runtime conditions for this Experiment.
+	// +listType=map
+	// +listMapKey=Type
```
Comment (andreyvelich) [inline pkg/apis/controller/experiments/v1beta1/experiment_types.go:84]: Same question for Type.

**Review by andreyvelich — COMMENTED** [review]
Thank you for this contribution @truc0!

**Review by andreyvelich — COMMENTED** [review]
Thank you for this great contribution @truc0!
/lgtm
/approve

**Comment by Electronic-Waste** [comment]
Thanks for your great contribution @truc0 ! And also, welcome to the Kubeflow Community! 🎉

Wish it a memorable journey for you to explore Kubeflow:)
